FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/master ./cmd/master

FROM alpine:3.21
RUN apk add --no-cache ca-certificates

COPY --from=builder /bin/master /bin/master

EXPOSE 8080

ENTRYPOINT ["/bin/master"]
